### ISSUE TITLE
项目导入报错

### ISSUE THREAD

**Issue by Cai-Go** [qiujuer/UPMiss#1]
![image](https://cloud.githubusercontent.com/assets/7565399/18516522/f9095998-7acb-11e6-9a08-f279254e3199.png)
看不懂你的配置文件

**Comment by qiujuer** [comment]
哦哦 这个有两个办法解决：
1.安装SDK24
2.更改所有的support包版本为23版本就好

**Comment by Cai-Go** [comment]
![image](https://cloud.githubusercontent.com/assets/7565399/18517785/182c66c2-7ad0-11e6-813f-77db6bcc2157.png)
请教下你的这个配置为啥是这样啊？表示不懂

**Comment by qiujuer** [comment]
这样的写法主要是为了项目中所有的module都统一进行更改，不用每个都去做修改，所以 可以修改根目录下的gradle.properties文件中的参数即可。同时也是为了方便协作。

**Comment by Cai-Go** [comment]
这样啊，学习了。谢谢啊 ：)

**Comment by qiujuer** [comment]
不客气，如果有BUG什么的欢迎提出来。
