### ISSUE TITLE
Error:(2, 0) Plugin with id 'com.neenbedankt.android-apt' not found

### ISSUE THREAD

**Issue by jaxtonzhc** [qiujuer/UPMiss#2]
when i import this project to android studio 2.2 RC 2,it come up with this error, how to solve this error?

**Comment by qiujuer** [comment]
你好，这个问题应该是你的网络问题导致的，可以尝试翻墙或者切换网络条件后重新导入即可；我这边 android studio 2.2 RC 2无任何问题。
